homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 31
  unit_system: metric
  time_zone: Australia/Perth
  customize: !include customize.yaml

zone 2:
  name: Office
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 100
  icon: mdi:briefcase

http:
  api_password: !secret api_password
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 2

frontend:
device_tracker:
config:
updater:
discovery:
conversation:
history:
logbook:
logger:
cloud:
map:
tts:
sun:

recorder: !include recorder.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
media_player: !include media_players.yaml
notify: !include notify.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
weblink: !include weblinks.yaml